package main

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"time"
)

// prPlan proposes locally edited installed-copy content back to the source
// repository as a branch + PR/MR. Merging (and conflict judgement) is
// deliberately left to the repository side: the TUI only detects and ships.
type prPlan struct {
	Remote     bool
	Repo       string // OWNER/REPO for remote sources
	SourceRoot string // clone root for local sources
	Branch     string
	CopyAgents string
	CopyDir    string
	SourceDirs []string // repo-relative dirs being EDITED
	DestDirs   []string // repo-relative dirs being ADDED (empty for edit plans)
	AddLines   []string // confirm-screen lines describing each addition
	Title      string
	Body       string
	Files      map[string]string // repo-root-relative path -> new content
	Deletes    []string          // repo-root-relative paths removed in the copy
	Changed    []string          // display list (M/A/D rel-path)
	Diff       string            // unified diff of SKILL.md, precomputed
	Outdated   bool
}

// applyPRTemplate replaces the generated PR/MR body with the configured
// pr_template file. {{body}} embeds the generated details and {{title}} the
// title; a template without {{body}} gets the details appended so the
// provenance the TUI collected is never silently dropped.
func applyPRTemplate(cfg config, projectRoot string, plan *prPlan) error {
	if cfg.PRTemplate == "" {
		return nil
	}
	path := expandHome(cfg.PRTemplate)
	if !filepath.IsAbs(path) {
		path = filepath.Join(projectRoot, path)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("pr_template: %v", err)
	}
	text := strings.ReplaceAll(string(data), "{{title}}", plan.Title)
	if strings.Contains(text, "{{body}}") {
		text = strings.ReplaceAll(text, "{{body}}", plan.Body)
	} else {
		text = strings.TrimRight(text, "\n") + "\n\n" + plan.Body
	}
	plan.Body = text
	return nil
}

// buildPRPlan picks the locally edited copy of the cursor skill (the cursor
// agent when the agents panel is focused, otherwise the first agent with
// local edits) and turns it into a branch/PR plan.
func (m model) buildPRPlan() (*prPlan, string) {
	s, ok := m.currentSkill()
	if !ok {
		return nil, "no skill under cursor"
	}
	return m.buildPRPlanForSkill(s)
}

// buildPRPlanForSkill builds one edit proposal without relying on panel
// focus or a visible cursor. Neutral selections may include hidden rows, so
// every resolver must operate on explicit skill identities.
func (m model) buildPRPlanForSkill(s skill) (*prPlan, string) {
	key := m.skillKey(s)

	var inst installedSkill
	var provName string
	found := false
	if m.focus == focusAgents && len(m.installTargets) > 0 {
		p := m.installTargets[m.cursors[focusAgents]]
		if candidate, ok := m.lookup.byKey[key][p.Short+"|"+m.scope]; ok && m.copyModified(candidate) {
			inst, provName, found = candidate, p.Name, true
		}
	}
	if !found {
		for _, p := range m.installTargets {
			if candidate, ok := m.lookup.byKey[key][p.Short+"|"+m.scope]; ok && m.copyModified(candidate) {
				inst, provName, found = candidate, p.Name, true
				break
			}
		}
	}
	if !found {
		return nil, "no locally edited copy in " + m.scope + " scope"
	}

	prefix := ""
	if m.sourceLocal {
		if out, err := runGit(m.sourceRoot, "rev-parse", "--show-prefix"); err == nil {
			prefix = strings.TrimSpace(out)
		}
	}

	files := make(map[string]string)
	copyRoot := resolveDirSymlink(inst.Dir)
	err := filepath.WalkDir(copyRoot, func(p string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		rel, err := filepath.Rel(copyRoot, p)
		if err != nil {
			return err
		}
		if junkRel(rel) {
			return nil
		}
		content, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		text := string(content)
		switch {
		case filepath.ToSlash(rel) == "SKILL.md" && s.Content != "":
			// keep the source frontmatter verbatim when only the body
			// changed, so the PR diff carries no serialization noise
			text = reconstructSkillMD(s.Content, text)
		case d.Name() == "SKILL.md":
			text = normalizeSkillMD(text)
		}
		files[prefix+s.Dir()+"/"+filepath.ToSlash(rel)] = text
		return nil
	})
	if err != nil {
		return nil, "cannot read copy: " + err.Error()
	}
	var deletes []string
	copySet := inst.FileShas
	for rel := range m.sourceFilesFor(key) {
		if _, ok := copySet[rel]; !ok {
			deletes = append(deletes, prefix+s.Dir()+"/"+rel)
		}
	}
	sort.Strings(deletes)

	outdated := inst.TreeSha != "" && m.treeShas[key] != "" && inst.TreeSha != m.treeShas[key]
	base := path.Base(s.Dir())
	branch := "gh-skill-tui/" + strings.ReplaceAll(base, "_", "-") + "-" + time.Now().Format("20060102-150405")
	title := fmt.Sprintf("skill: %s (edited on %s copy)", base, provName)

	var body strings.Builder
	fmt.Fprintf(&body, "Generated by gh-skill-tui from a locally edited installed copy.\n\n")
	fmt.Fprintf(&body, "- source skill: `%s`\n", s.Dir())
	fmt.Fprintf(&body, "- copy taken from: `%s` (%s, %s scope)\n", homeShorten(inst.Dir), provName, m.scope)
	if inst.TreeSha != "" {
		fmt.Fprintf(&body, "- installed at tree: `%.12s`\n", inst.TreeSha)
	}
	if cur := m.treeShas[key]; cur != "" {
		fmt.Fprintf(&body, "- source tree now: `%.12s`\n", cur)
	}
	if outdated {
		fmt.Fprintf(&body, "\n⚠ **source has moved since install** — this diff may revert newer upstream changes. Review carefully before merging.\n")
	}

	diff := ""
	if s.Content != "" && inst.SkillMD != "" {
		if d, err := diffTexts(s.Content, reconstructSkillMD(s.Content, inst.SkillMD)); err == nil {
			diff = d
		}
	}

	return &prPlan{
		Remote:     !m.sourceLocal,
		Repo:       m.cfg.Source,
		SourceRoot: m.sourceRoot,
		Branch:     branch,
		CopyAgents: provName,
		CopyDir:    inst.Dir,
		SourceDirs: []string{s.Dir()},
		Title:      title,
		Body:       body.String(),
		Files:      files,
		Deletes:    deletes,
		Changed:    m.copyChanges(inst),
		Diff:       diff,
		Outdated:   outdated,
	}, ""
}

// buildSelectedPRPlan resolves one neutral selection into a single atomic PR
// plan. Edited managed skills and outside imports may share the PR. Any
// incompatible target or destination problem blocks execution, while valid
// work remains visible in the plan as Ready work.
func (m model) buildSelectedPRPlan(selected []skill, outside []localOnlySkill) (*prPlan, []string) {
	var parts []*prPlan
	var blocks []string
	for _, s := range selected {
		plan, errMsg := m.buildPRPlanForSkill(s)
		if plan == nil {
			blocks = append(blocks, s.Dir()+": "+errMsg)
			continue
		}
		parts = append(parts, plan)
	}
	var addItems []addItem
	for _, lo := range outside {
		cp, errMsg := m.resolveOutsideCopy(lo)
		if errMsg != "" {
			blocks = append(blocks, errMsg)
			continue
		}
		dest, err := m.autoDestDir(cp)
		if err != nil {
			blocks = append(blocks, lo.Name+": "+err.Error())
			continue
		}
		addItems = append(addItems, addItem{Copy: cp, Dest: dest})
	}
	if len(addItems) > 0 {
		plan, errMsg := m.buildBatchAddPRPlan(addItems)
		if plan == nil {
			blocks = append(blocks, errMsg)
		} else {
			parts = append(parts, plan)
		}
	}
	plan, errMsg := mergePRPlans(parts)
	if errMsg != "" {
		blocks = append(blocks, errMsg)
		return nil, blocks
	}
	return plan, blocks
}

func mergePRPlans(parts []*prPlan) (*prPlan, string) {
	if len(parts) == 0 {
		return nil, ""
	}
	if len(parts) == 1 {
		return parts[0], ""
	}
	first := parts[0]
	targetCount := 0
	for _, p := range parts {
		targetCount += len(p.SourceDirs) + len(p.DestDirs)
	}
	if targetCount == 0 {
		targetCount = len(parts)
	}
	merged := &prPlan{
		Remote:     first.Remote,
		Repo:       first.Repo,
		SourceRoot: first.SourceRoot,
		Branch:     fmt.Sprintf("gh-skill-tui/propose-%d-skills-%s", targetCount, time.Now().Format("20060102-150405")),
		CopyAgents: fmt.Sprintf("%d selected skills", targetCount),
		Title:      fmt.Sprintf("skill: propose %d selected skills", targetCount),
		Files:      make(map[string]string),
	}
	var body, diffs strings.Builder
	body.WriteString("Generated by gh-skill-tui from selected edited and outside copies.\n")
	deleteSeen := make(map[string]bool)
	for i, p := range parts {
		if p.Remote != merged.Remote || p.Repo != merged.Repo || p.SourceRoot != merged.SourceRoot {
			return nil, "selected PR targets resolve to different source repositories"
		}
		for name, content := range p.Files {
			if deleteSeen[name] {
				return nil, "PR target is both written and deleted: " + name
			}
			if _, exists := merged.Files[name]; exists {
				return nil, "duplicate PR target path: " + name
			}
			merged.Files[name] = content
		}
		for _, name := range p.Deletes {
			if _, exists := merged.Files[name]; exists {
				return nil, "PR target is both written and deleted: " + name
			}
			if !deleteSeen[name] {
				deleteSeen[name] = true
				merged.Deletes = append(merged.Deletes, name)
			}
		}
		merged.SourceDirs = append(merged.SourceDirs, p.SourceDirs...)
		merged.DestDirs = append(merged.DestDirs, p.DestDirs...)
		if len(p.AddLines) > 0 {
			merged.AddLines = append(merged.AddLines, p.AddLines...)
		} else {
			for _, dir := range p.SourceDirs {
				merged.AddLines = append(merged.AddLines, fmt.Sprintf("edits:   %s/  (from %s)", dir, homeShorten(p.CopyDir)))
			}
		}
		for _, changed := range p.Changed {
			fields := strings.SplitN(strings.TrimSpace(changed), " ", 2)
			if len(p.SourceDirs) == 1 && len(fields) == 2 &&
				!strings.HasPrefix(fields[1], p.SourceDirs[0]+"/") {
				changed = fields[0] + " " + path.Join(p.SourceDirs[0], fields[1])
			}
			merged.Changed = append(merged.Changed, changed)
		}
		merged.Outdated = merged.Outdated || p.Outdated
		body.WriteString("\n\n---\n\n")
		body.WriteString(p.Body)
		if p.Diff != "" {
			if diffs.Len() > 0 {
				diffs.WriteString("\n")
			}
			fmt.Fprintf(&diffs, "### change %d\n%s", i+1, p.Diff)
		}
	}
	sort.Strings(merged.Deletes)
	sort.Strings(merged.Changed)
	merged.Body = body.String()
	merged.Diff = diffs.String()
	return merged, ""
}

// addItem pairs an outside-source copy with its destination dir in the source.
type addItem struct {
	Copy localCopy
	Dest string
}

// buildAddPRPlan turns one outside-source installed copy into a branch/PR plan
// that ADDS the skill to the source repository at destDir.
func (m model) buildAddPRPlan(cp localCopy, destDir string) (*prPlan, string) {
	return m.buildBatchAddPRPlan([]addItem{{Copy: cp, Dest: destDir}})
}

// buildBatchAddPRPlan bundles one or more outside-source copies into a single
// branch/PR plan adding them to the source. There is no source counterpart,
// so every file ships as an addition and no outdated warning applies.
func (m model) buildBatchAddPRPlan(items []addItem) (*prPlan, string) {
	if len(items) == 0 {
		return nil, "nothing to add"
	}
	prefix := ""
	if m.sourceLocal {
		if out, err := runGit(m.sourceRoot, "rev-parse", "--show-prefix"); err == nil {
			prefix = strings.TrimSpace(out)
		}
	}

	files := make(map[string]string)
	var changed, dests, addLines, names, diffs []string
	var bodyItems strings.Builder
	seenDest := make(map[string]bool)
	for _, it := range items {
		inst := it.Copy.Inst
		if seenDest[it.Dest] {
			return nil, "duplicate destination: " + it.Dest
		}
		seenDest[it.Dest] = true
		copyRoot := resolveDirSymlink(inst.Dir)
		n := 0
		err := filepath.WalkDir(copyRoot, func(p string, d os.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return err
			}
			rel, err := filepath.Rel(copyRoot, p)
			if err != nil {
				return err
			}
			if junkRel(rel) {
				return nil
			}
			content, err := os.ReadFile(p)
			if err != nil {
				return err
			}
			text := string(content)
			if d.Name() == "SKILL.md" {
				// strip whatever tracking metadata a tool may have
				// injected; untracked copies usually carry none
				text = normalizeSkillMD(text)
			}
			files[prefix+it.Dest+"/"+filepath.ToSlash(rel)] = text
			changed = append(changed, "A "+it.Dest+"/"+filepath.ToSlash(rel))
			n++
			return nil
		})
		if err != nil {
			return nil, "cannot read copy: " + err.Error()
		}
		if n == 0 {
			return nil, "copy is empty: " + inst.Dir
		}
		provName := strings.Join(it.Copy.Agents, "+")
		dests = append(dests, it.Dest)
		names = append(names, path.Base(it.Dest))
		addLines = append(addLines, fmt.Sprintf("adds:    %s/  (from %s)", it.Dest, homeShorten(inst.Dir)))
		fmt.Fprintf(&bodyItems, "- new skill: `%s` — copy from `%s` (%s, %s scope)\n", it.Dest, homeShorten(inst.Dir), provName, it.Copy.Scope)
		if inst.RepoSlug != "" {
			fmt.Fprintf(&bodyItems, "  - original repository metadata: `%s`\n", inst.RepoSlug)
		}
		if inst.SkillMD != "" {
			if d, err := diffTexts("", normalizeSkillMD(inst.SkillMD)); err == nil && d != "" {
				if len(items) > 1 {
					diffs = append(diffs, "### "+it.Dest+"/SKILL.md")
				}
				diffs = append(diffs, d)
			}
		}
	}
	sort.Strings(changed)

	ts := time.Now().Format("20060102-150405")
	branch := "gh-skill-tui/add-" + strings.ReplaceAll(names[0], "_", "-") + "-" + ts
	title := fmt.Sprintf("skill: add %s (from %s copy)", names[0], strings.Join(items[0].Copy.Agents, "+"))
	provName := strings.Join(items[0].Copy.Agents, "+")
	if len(items) > 1 {
		branch = fmt.Sprintf("gh-skill-tui/add-%d-skills-%s", len(items), ts)
		title = "skill: add " + strings.Join(names, ", ")
		provName = fmt.Sprintf("%d local copies", len(items))
	}

	var body strings.Builder
	fmt.Fprintf(&body, "Generated by gh-skill-tui from outside-source installed copies.\n\n")
	body.WriteString(bodyItems.String())

	return &prPlan{
		Remote:     !m.sourceLocal,
		Repo:       m.cfg.Source,
		SourceRoot: m.sourceRoot,
		Branch:     branch,
		CopyAgents: provName,
		CopyDir:    items[0].Copy.Inst.Dir,
		DestDirs:   dests,
		AddLines:   addLines,
		Title:      title,
		Body:       body.String(),
		Files:      files,
		Changed:    changed,
		Diff:       strings.Join(diffs, "\n"),
	}, ""
}

func (m model) prConfirmContent(w int) (string, []string) {
	p := m.prPlan
	target := p.Repo
	if !p.Remote {
		target = homeShorten(p.SourceRoot) + " (git push -o merge_request.create)"
	}
	lines := []string{
		"branch:  " + p.Branch,
		"target:  " + target,
	}
	if len(p.AddLines) > 0 {
		lines = append(lines, p.AddLines...)
	} else {
		lines = append(lines, "from:    "+homeShorten(p.CopyDir)+" ("+p.CopyAgents+")")
	}
	lines = append(lines, "")
	if p.Outdated {
		lines = append(lines, errorStyle.Render("⚠ source has moved since install — diff may revert upstream changes"), "")
	}
	lines = append(lines, "changed files:")
	for _, c := range p.Changed {
		lines = append(lines, "  "+c)
	}
	if len(p.Deletes) > 0 {
		lines = append(lines, fmt.Sprintf("  (%d deletion(s) included)", len(p.Deletes)))
	}
	lines = append(lines, "")
	cacheKey := fmt.Sprintf("pr|%s|%d", p.Branch, w)
	diffLines, ok := m.diffCache[cacheKey]
	if !ok {
		diffLines = renderDiff(p.Diff, w)
		m.diffCache[cacheKey] = diffLines
	}
	if len(diffLines) > 0 {
		lines = append(lines, diffLines...)
	} else {
		lines = append(lines, mutedStyle.Render("(no SKILL.md text diff available)"))
	}
	switch {
	case len(p.SourceDirs) > 0 && len(p.DestDirs) > 0:
		return fmt.Sprintf("PR plan (%d edits + %d additions)", len(p.SourceDirs), len(p.DestDirs)), lines
	case len(p.DestDirs) > 1:
		return fmt.Sprintf("PR plan (add %d skills)", len(p.DestDirs)), lines
	case len(p.DestDirs) == 1:
		return "PR plan (add skill)", lines
	}
	return "PR plan", lines
}

// renderDiff turns a unified diff into display lines. With diff_command set
// in the config (e.g. "delta --color-only --paging=never") the diff is piped
// through it and its ANSI output is shown as-is; otherwise a built-in
// colorizer is used.
func renderDiff(diff string, w int) []string {
	diff = strings.TrimRight(diff, "\n")
	if diff == "" {
		return nil
	}
	var out []string
	if diffCommand := activeFileConfig().DiffCommand; diffCommand != "" {
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		cmd := exec.CommandContext(ctx, "sh", "-c", diffCommand)
		cmd.Stdin = strings.NewReader(diff + "\n")
		cmd.Env = append(os.Environ(), fmt.Sprintf("COLUMNS=%d", w))
		// detach from the terminal: tools like delta query the tty for
		// its background color and would block under the TUI
		cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
		var stderr strings.Builder
		cmd.Stderr = &stderr
		if outBytes, err := cmd.Output(); err == nil {
			return strings.Split(strings.TrimRight(string(outBytes), "\n"), "\n")
		} else {
			// fall back to the built-in colorizer, but say why
			msg := strings.TrimSpace(stderr.String())
			if msg == "" {
				msg = err.Error()
			}
			out = append(out, mutedStyle.Render(truncate("(diff_command failed: "+msg+")", w)))
		}
	}
	for _, line := range strings.Split(diff, "\n") {
		// machine header lines add nothing for a human reading the panel
		if strings.HasPrefix(line, "diff --git") || strings.HasPrefix(line, "index ") {
			continue
		}
		for _, wrapped := range wrapLines(line, w) {
			switch {
			case strings.HasPrefix(line, "+"):
				out = append(out, markStyle.Render(wrapped))
			case strings.HasPrefix(line, "-"):
				out = append(out, errorStyle.Render(wrapped))
			case strings.HasPrefix(line, "@@"):
				out = append(out, headingStyle.Render(wrapped))
			default:
				out = append(out, mutedStyle.Render(wrapped))
			}
		}
	}
	return out
}

// diffTexts runs `git diff --no-index` over the two texts and relabels the
// temp-file headers as source/installed.
func diffTexts(source, installed string) (string, error) {
	git, err := commandPath("git")
	if err != nil {
		return "", err
	}
	writeTemp := func(content string) (string, error) {
		f, err := os.CreateTemp("", "gh-skill-tui-diff-*")
		if err != nil {
			return "", err
		}
		if _, err := f.WriteString(content); err != nil {
			if closeErr := f.Close(); closeErr != nil {
				return "", fmt.Errorf("write temporary diff file: %w (close: %v)", err, closeErr)
			}
			return "", err
		}
		return f.Name(), f.Close()
	}
	a, err := writeTemp(source)
	if err != nil {
		return "", err
	}
	defer func() { _ = os.Remove(a) }()
	b, err := writeTemp(installed)
	if err != nil {
		return "", err
	}
	defer func() { _ = os.Remove(b) }()
	// exit status 1 just means "files differ"
	out, _ := exec.Command(git, "diff", "--no-index", "--no-color", "--unified=3", "--", a, b).Output()
	// keep the full git-style structure (diff-so-fancy hard-requires the
	// diff --git header) but relabel the temp files in the a/-b/
	// convention so tools report "modified: SKILL.md". Only the first
	// ---/+++ pair is a header (git may render the temp paths with or
	// without the a/-b/ prefix depending on version); later matches would
	// be body lines.
	var lines []string
	relabeledA, relabeledB := false, false
	for _, line := range strings.Split(string(out), "\n") {
		switch {
		case strings.HasPrefix(line, "diff --git"):
			line = "diff --git a/SKILL.md b/SKILL.md"
		case !relabeledA && strings.HasPrefix(line, "--- "):
			line = "--- a/SKILL.md"
			relabeledA = true
		case !relabeledB && strings.HasPrefix(line, "+++ "):
			line = "+++ b/SKILL.md"
			relabeledB = true
		}
		lines = append(lines, line)
	}
	return strings.Join(lines, "\n"), nil
}

// runPR executes a PR plan and returns a one-line summary (PR URL for
// GitHub, branch info for local pushes). The tea.Exec wrapper owns terminal
// presentation, so these helpers return captured diagnostics to the caller.
func runPR(plan prPlan) (string, error) {
	if plan.Remote {
		return runPRRemote(plan)
	}
	return runPRLocal(plan)
}

// runPRLocal builds the branch with git plumbing only (temporary index, no
// working-tree changes) and pushes with GitLab merge-request push options.
func runPRLocal(plan prPlan) (string, error) {
	root := plan.SourceRoot
	baseOut, err := runGit(root, "rev-parse", "HEAD")
	if err != nil {
		return "", err
	}
	base := strings.TrimSpace(baseOut)

	idx, err := os.CreateTemp("", "gh-skill-tui-index-*")
	if err != nil {
		return "", err
	}
	idxPath := idx.Name()
	if err := idx.Close(); err != nil {
		return "", fmt.Errorf("close temporary index: %w", err)
	}
	if err := os.Remove(idxPath); err != nil && !os.IsNotExist(err) {
		return "", fmt.Errorf("remove temporary index: %w", err)
	}
	defer func() { _ = os.Remove(idxPath) }()
	env := []string{"GIT_INDEX_FILE=" + idxPath}

	if _, err := runGitFull(root, env, "", "read-tree", "HEAD"); err != nil {
		return "", err
	}
	var paths []string
	for p := range plan.Files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		shaOut, err := runGitFull(root, nil, plan.Files[p], "hash-object", "-w", "--stdin")
		if err != nil {
			return "", err
		}
		sha := strings.TrimSpace(shaOut)
		if _, err := runGitFull(root, env, "", "update-index", "--add", "--cacheinfo", "100644,"+sha+","+p); err != nil {
			return "", err
		}
	}
	for _, d := range plan.Deletes {
		if _, err := runGitFull(root, env, "", "update-index", "--force-remove", d); err != nil {
			return "", err
		}
	}
	treeOut, err := runGitFull(root, env, "", "write-tree")
	if err != nil {
		return "", err
	}
	commitOut, err := runGitFull(root, nil, plan.Title+"\n\n"+plan.Body, "commit-tree", strings.TrimSpace(treeOut), "-p", base, "-F", "-")
	if err != nil {
		return "", err
	}
	commit := strings.TrimSpace(commitOut)
	if _, err := runGit(root, "update-ref", "refs/heads/"+plan.Branch, commit); err != nil {
		return "", err
	}

	target := "main"
	if out, err := runGit(root, "symbolic-ref", "--short", "refs/remotes/origin/HEAD"); err == nil {
		target = strings.TrimPrefix(strings.TrimSpace(out), "origin/")
	}
	if _, err := runGit(root, "push", "-u", "origin", plan.Branch,
		"-o", "merge_request.create", "-o", "merge_request.target="+target); err != nil {
		// e.g. the receiving end does not support push options
		if _, err2 := runGit(root, "push", "-u", "origin", plan.Branch); err2 != nil {
			return "", fmt.Errorf("branch %s created locally but push failed: %v", plan.Branch, err2)
		}
		return "branch " + plan.Branch + " pushed (plain push; MR options unsupported)", nil
	}
	return "MR branch " + plan.Branch + " pushed (target: " + target + ")", nil
}

// runPRRemote builds the branch through the GitHub git data API (no clone
// needed) and opens the PR with gh, returning the PR URL.
func runPRRemote(plan prPlan) (string, error) {
	repo := plan.Repo
	defBranch, err := defaultRef(repo)
	if err != nil {
		return "", err
	}
	baseSha, err := runGh("api", "repos/"+repo+"/git/ref/heads/"+defBranch, "--jq", ".object.sha")
	if err != nil {
		return "", err
	}
	baseSha = strings.TrimSpace(baseSha)
	baseTree, err := runGh("api", "repos/"+repo+"/git/commits/"+baseSha, "--jq", ".tree.sha")
	if err != nil {
		return "", err
	}
	baseTree = strings.TrimSpace(baseTree)

	type treeEntry struct {
		Path string  `json:"path"`
		Mode string  `json:"mode"`
		Type string  `json:"type"`
		Sha  *string `json:"sha"`
	}
	var entries []treeEntry
	var paths []string
	for p := range plan.Files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		blobBody, err := json.Marshal(map[string]string{
			"content":  base64.StdEncoding.EncodeToString([]byte(plan.Files[p])),
			"encoding": "base64",
		})
		if err != nil {
			return "", err
		}
		blobSha, err := runGhInput(string(blobBody), "api", "repos/"+repo+"/git/blobs", "--input", "-", "--jq", ".sha")
		if err != nil {
			return "", err
		}
		sha := strings.TrimSpace(blobSha)
		entries = append(entries, treeEntry{Path: p, Mode: "100644", Type: "blob", Sha: &sha})
	}
	for _, d := range plan.Deletes {
		entries = append(entries, treeEntry{Path: d, Mode: "100644", Type: "blob", Sha: nil})
	}

	treeBody, err := json.Marshal(map[string]any{"base_tree": baseTree, "tree": entries})
	if err != nil {
		return "", err
	}
	newTree, err := runGhInput(string(treeBody), "api", "repos/"+repo+"/git/trees", "--input", "-", "--jq", ".sha")
	if err != nil {
		return "", err
	}
	commitBody, err := json.Marshal(map[string]any{
		"message": plan.Title + "\n\n" + plan.Body,
		"tree":    strings.TrimSpace(newTree),
		"parents": []string{baseSha},
	})
	if err != nil {
		return "", err
	}
	newCommit, err := runGhInput(string(commitBody), "api", "repos/"+repo+"/git/commits", "--input", "-", "--jq", ".sha")
	if err != nil {
		return "", err
	}
	refBody, err := json.Marshal(map[string]string{
		"ref": "refs/heads/" + plan.Branch,
		"sha": strings.TrimSpace(newCommit),
	})
	if err != nil {
		return "", err
	}
	if _, err := runGhInput(string(refBody), "api", "repos/"+repo+"/git/refs", "--input", "-"); err != nil {
		return "", err
	}

	gh, err := commandPath("gh")
	if err != nil {
		return "", err
	}
	// run non-interactively: the TUI owns the terminal while this executes
	cmd := exec.Command(gh, "pr", "create", "--repo", repo,
		"--head", plan.Branch, "--base", defBranch,
		"--title", plan.Title, "--body", plan.Body)
	cmd.Env = append(os.Environ(), "GH_PROMPT_DISABLED=1", "GH_NO_UPDATE_NOTIFIER=1")
	var out, errb strings.Builder
	cmd.Stdout = &out
	cmd.Stderr = &errb
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(errb.String())
		if msg == "" {
			msg = err.Error()
		}
		return "", fmt.Errorf("branch %s pushed but gh pr create failed: %s", plan.Branch, msg)
	}
	return "PR created: " + strings.TrimSpace(out.String()), nil
}
